{% set name = "foundry-dev-tools" %}
{% set version = "1.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/foundry-dev-tools-{{ version }}.tar.gz
  sha256: 590c7a7314e05935eec4921d0780596002e939063e26fed06803fb181b39c8ab

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - setuptools >=46.1.0
    - setuptools-scm >=5
    - pip
  run:
    - python >=3.8,<4.0
    - pyarrow
    - pandas
    - requests
    - fs
    - backoff
    - palantir-oauth-client

test:
  imports:
    - foundry_dev_tools
    - transforms
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/emdgroup/foundry-dev-tools
  summary: Seamlessly run your Palantir Foundry Repository transforms code on your local machine.
  dev_url: https://github.com/emdgroup/foundry-dev-tools
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nicornk
    - jonas-w
